### ISSUE TITLE
Timezone option not working

### ISSUE THREAD

**Issue by dauledk** [node-cron/node-cron#109]
So I am trying to adopt `node-cron`, but I don't think the timezone setting is working, or maybe I am doing something wrong. I am based in Copehagen, Denmark i.e. timezone `Europe/Copenhagen`.

Consider the following code, to **reproduce**:

```
import * as cron from 'node-cron';

const getCurrentHour = new Date().getHours();
const oneMinuteInTheFuture = (new Date().getMinutes() === 60) ? 0 : new Date().getMinutes() + 1;

const pattern = `${oneMinuteInTheFuture} ${getCurrentHour} * * *`;
console.log(pattern);

const b = cron.schedule(pattern, () => {
        console.log('Timezone running');
    }, {
        timezone: 'Europe/Copenhagen',
        scheduled: false,
    });

const a = cron.schedule(pattern, () => {
    console.log('no-timezone running!');
}, {scheduled: false});

const start = () => {
    b.start();
    a.start();
};

start();
```

If you run this, and wait one minute, the **output** is:

```
no-timezone running!
```

And not as **expected output**: 

```
Timezone running
no-timezone running!
```

Is this because the timezone option, only works as I expect if the computer is running UTC time or what is the explanation?

**Comment by merencia** [comment]
Hello @dauledk 

By default, `node-cron` uses the system time. So in the fist example, `node-cron` has used the `Europe/Copenhagen`. In the second example, `node-cron` has used your machine timezone.

**Comment by merencia** [comment]
Hello @dauledk I've closed the issue for now, if you have some problem let me know.

**Comment by PoojaS-Hexaware** [comment]
Hi, node-cron is not working for a few of the specific timezones. Do we have any solution to run cron for all the timezones
?

**Comment by alterthedeveloper26** [comment]
![image](https://user-images.githubusercontent.com/55936436/166086535-95cf7c43-2b9a-482c-8ac2-ea64677b38b6.png)
This is the code of my cronjob, this is my time zone "Asia/Ho_Chi_Minh", i expected it to match to my machine time but it doesn't, in fact it is later than 8 hours. Am i doing anything wrong or it does not support Viet Name timezone?
