### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by merencia** [node-cron/node-cron#110]
As explained in [this issue](https://github.com/node-cron/node-cron/issues/108), the new `node-cron` version had a breaking change.

The third param, of `schedule` function, `immediateStart` was removed and replaced by a options.

The behavior of `immediateStart` was replaced by the option `scheduled`. 

So, to fix this issue we had two options:

1 - Update the lib https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node-cron

2 - Introduce a typings on `node-cron` project.

**Comment by jacob-hd** [comment]
Typings would be great.

**Comment by renatoalencar** [comment]
I think that we can replace declared methods inside the constructor by prototyped methods.

For example, instead of having this:

```js
function ScheduledTask(task, options) {
...
  this.getStatus = () => {
    return this.status;
  };
```

We would have this: 

```js
function ScheduledTask(task, options) {
...
ScheduledTask.prototype.getStatus = function () {
  return this.status;
}
```

**Comment by merencia** [comment]
Hey @renatoalencar 

We have a branch `v3` where we are doing some refactor and adding the new features, in that brach we also moving to classes.

The ideia is keep node-cron compatible with node 8.x, cause it's a LTS version and has support to classes. What do you think?

**Comment by renatoalencar** [comment]
Oh, great. So, I have just on question.

Why do something like this:

```js
this.start = () => {
  scheduler.start();
};
```

Instead of using methods?
