### ISSUE TITLE
DST support

### ISSUE THREAD

**Issue by merencia** [node-cron/node-cron#111]
Is possible to use the date timezone offset to check if the current date is in DST period.

How do that:
 - Create a date on Jan first;
 - Create a date on Jul first;
 - Get the lower offset of the two dates;
 - Create a new date to get the current date;
 - If the current date offset is equal the lower one, is DST period.

Why is this useful?
To prevent missing and duplicate executions on DST changes.

**Comment by GabrielCzar** [comment]
There are cities where DST does not exist, so they have equal time zones always. For these cases, the algorithm described would return the existence of a DST where it does not exist.

I believe that algorithm below prevent this.
```js
Date.prototype.stdTimezoneOffset = function() {
    var jan = new Date(this.getFullYear(), 0, 1);
    var jul = new Date(this.getFullYear(), 6, 1);
    
    return Math.max(jan.getTimezoneOffset(), jul.getTimezoneOffset());
}

Date.prototype.isDst = function() {
    return this.getTimezoneOffset() < this.stdTimezoneOffset();
}
```
