### ISSUE TITLE
Run At Every Minute of A Given Hour

### ISSUE THREAD

**Issue by japita-se** [node-cron/node-cron#113]
This simple rule:
`cron.schedule("* 12 * *  1-5", () => {})`

does not fire any event.
I was supposed that it should fire at every minute of the hour 12.

**Comment by merencia** [comment]
Hey @japita-se 

I did test:

My current hour is 10, so:

```js
const cron = require('node-cron');

cron.schedule("* 10 * * 1-5", () => {
  console.log('every minute');
});

```

And it works fine:
![image](https://user-images.githubusercontent.com/1686635/46671476-4870d380-cbab-11e8-93ce-3d6a948eeb63.png)

**Comment by japita-se** [comment]
I forgot to say that I set also the timezone option to Europe/Rome (which is my current timezone).
