### ISSUE TITLE
Is node-cron block event loop ?

### ISSUE THREAD

**Issue by armenmargaryan** [node-cron/node-cron#114]
Hello,

This sis actually a question not issue
pardon me if i'm posting in wrong place

But is node-cron block event loop during executing code when defined time come ?
or it works somehow asynchronously ?

Thank you,
Armen

**Comment by merencia** [comment]
Hello @armenmargaryan 
Internally node-cron performs the given function asynchronously, inside a `setTimeout`.
But if inside your function you do some block io, as a `for`, it'll block all your thread.

**Comment by armenmargaryan** [comment]
ok its clear.
one more question is there a way to **run node cron by using child_process** ???

**Comment by merencia** [comment]
@armenmargaryan I've created another project to do that: https://sidequestjs.com/ but I did't release yet.

Actually I thinking about to merge sidequest with node-cron to provide a native way to do that.

**Comment by Rajat-Bansal3** [comment]
i know i am reviving after a really long time but wont using async callback to original function solve that ? because i just came across this issue and i tried that
