### ISSUE TITLE
TimeZone Europe/Rome Not Working

### ISSUE THREAD

**Issue by japita-se** [node-cron/node-cron#115]
I am trying the nodecron in Italy and I set the timezone to Europe/Rome.
No cron strings are working.
If I do not set the timeone, everything is fine.
Why?

**Comment by merencia** [comment]
Hello @japita-se 

It may be a bug, may you send me an example? And how are your current timezone?

**Comment by japita-se** [comment]
My current timezone is Europe/Rome.
The example is very basic:
`cron.schedule ("*/1 12 * * Monday-Sunday", () => console.log("Ehi!"), {timezone:'Europe/Rome'})`

**Comment by merencia** [comment]
Hey, I'm wondering about this issue, are you in daylight saving time?

**Comment by felixheck** [comment]
Got the same bug for `Europe/Berlin` — it triggers one hour before the scheduled time because it's using CET instead of CEST.

**Comment by felixheck** [comment]
Switched to cron for now.  
Seems to handle CEST correctly.

**Comment by merencia** [comment]
@felixheck thanks for getting in touch. 
Node-cron will support DST soon, I've created this issue https://github.com/node-cron/node-cron/issues/111 to do that.

**Comment by felixheck** [comment]
@merencia drop a line asa it’s available 😉 node-cron has a much better documentation and a better syntax imho. But without DST it’s currently kinda useless for me. 

Keep me updated. 
Thanks!

**Comment by alanclarke** [comment]
@merencia `America/Vancouver` is also missing

**Comment by alanclarke** [comment]
Unfortunately it doesn't seem possible to catch and handle this edge case, because it happens in a setTimeout

**Comment by benjamin21st** [comment]
`America/New_York` doesn't seem to work either. 
![Screen Shot 2019-10-21 at 1 57 37 PM](https://user-images.githubusercontent.com/8607086/67230169-c72d5d00-f40a-11e9-8c1d-a5581990fc0a.png)

**Comment by merencia** [comment]
moving to moment-timezone https://github.com/node-cron/node-cron/pull/248
