### ISSUE TITLE
Installing fails with "opencollective-postinstall: command not found"

### ISSUE THREAD

**Issue by chrisEff** [node-cron/node-cron#117]
Just tried to install node-cron from npm, but couldn't. Here's the complete console output:
```
npm i node-cron
> node-cron@2.0.2 postinstall /Users/johndoe/dev/home/home-server-nodejs/node_modules/node-cron
> opencollective-postinstall

sh: opencollective-postinstall: command not found

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! node-cron@2.0.2 postinstall: `opencollective-postinstall`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-cron@2.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/johndoe/.npm/_logs/2018-10-09T20_27_48_949Z-debug.log
```

**Comment by chrisEff** [comment]
Oh hey, and I was able to reproduce it on MacOS and Raspbian, if that helps.

**Comment by chrisEff** [comment]
Been able to work around it by manually installing opencollective-postinstall first. So I guess it's just missing in your dependencies.

**Comment by Sridatta19** [comment]
+1

**Comment by kn1cht** [comment]
`opencollective-postinstall` should be in dependencies, not in devDependencies.

https://github.com/node-cron/node-cron/blob/f451a8df8974407c1ff1e80378a32854502de911/package.json#L32-L40

**Comment by merencia** [comment]
Thanks for fix that @chrisEff 
I just released a new version (2.0.3) with this bugfix.

**Comment by Sluder** [comment]
Still seems to be an issue in v2.0.3 
`npm ERR! node-cron@2.0.3 postinstall: `opencollective-postinstall`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the node-cron@2.0.3 postinstall script.
`

**Comment by zuwagon** [comment]
@merencia Apparently, this bus is in version 2.0.3 too

**Comment by praveshtora** [comment]
I am still facing this issue in 2.0.3.

**Comment by sharon12312** [comment]
+1

**Comment by tomeady** [comment]
Have hit this error in 2.0.3 on Windows.

**Comment by itxtoledo** [comment]
having this error in ubuntu on google cloud

**Comment by PiyushGargOfficial** [comment]
error of opencollective-postinstall

**Comment by danishn** [comment]
having this error in ubuntu on google cloud

`npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! node-cron@2.0.3 postinstall: `opencollective-postinstall`
npm ERR! Exit status 126
npm ERR!
npm ERR! Failed at the node-cron@2.0.3 postinstall script.`

**Comment by himav** [comment]
Facing the same issue. Is there a way to bypass this error?

**Comment by deadpassive** [comment]
> Facing the same issue. Is there a way to bypass this error?

It works for me if I include opencollective-postinstall in my own dependencies

**Comment by nandarora-compro** [comment]
Yup, installed opencollective-postinstall first and then the node-cron package. It worked like a charm.

**Comment by kpatrick** [comment]
I just wasted an entire day on this "closed" bug.

**Comment by kpatrick** [comment]
My CI system had 2.0.3 version with the  opencollective-postinstall  as a dependency.  Perhaps code was push twice with the same version number.  Now CI is poisoned.

**Comment by ryanburnette** [comment]
+1

**Comment by thanhthinh95** [comment]
Currently, this error still occurs for windows.
node: 12.10.0
npm: 6.11.3

**Comment by johnalotoski** [comment]
No more of these errors now with node-cron 3.0.0.
