### ISSUE TITLE
Allows custom execution check  frequency.

### ISSUE THREAD

**Issue by merencia** [node-cron/node-cron#121]
This issue refs to #120

In this issue node-cron will receive by options the `executionCheckFrequency`, this value will be used on `scheduler` here https://github.com/node-cron/node-cron/blob/06970fba03307edd2fe775e0b8c690b7e6e4867b/src/scheduler.js#L22 and here https://github.com/node-cron/node-cron/blob/06970fba03307edd2fe775e0b8c690b7e6e4867b/src/scheduler.js#L26

If not passed the default value is `1000`.

**Important**: If the frequency is less than 1s, is necessary to avoid multiples executions in the same second.

**Comment by merencia** [comment]
I'll close this issue for now.

**Comment by TDola** [comment]
Sorry was occupied.
Important is difficult to answer.  If someone only needs a schedule every minute, they might set the execution frequency to 1000 * 60.  So it's still a possibility.  Your right in that bad values will cause problems, but in that case, it's garbage in = garbage out.
