### ISSUE TITLE
is there a list of the timezone names?

### ISSUE THREAD

**Issue by LeonTheLeon** [node-cron/node-cron#124]
hey is there any list on the timezone codes from node-cron?
i want it to do a thing at midnight in the CET timezone
but the name of that isnt written down anywhere
and i have tried just putting "CET" and "Europe" and neither worked
i havent found anything

**Comment by merencia** [comment]
Hello, `node-cron` uses the the [tz-offset](https://github.com/node-cron/tz-offset) to handle timezones.

There is a JSON with all available timezones https://github.com/node-cron/tz-offset/blob/master/generated/offsets.json

**Comment by LeonTheLeon** [comment]
thanks

**Comment by anil357** [comment]
Thanks a lot...

**Comment by johnmalatras** [comment]
tz-offset has been updated with new timezones, however node-cron still uses the old version and therefore the above linked list includes unsupported timezones. [Here](https://raw.githubusercontent.com/node-cron/tz-offset/a67968ab5b0efa6dee296dac32d3205b41f158e0/generated/offsets.json) is a link to the 0.0.1 list which node-cron supports

**Comment by Leigh-Ola** [comment]
> 
> 
> tz-offset has been updated with new timezones, however node-cron still uses an old version (0.0.1) and therefore the above linked list includes unsupported timezones. [Here](https://raw.githubusercontent.com/node-cron/tz-offset/a67968ab5b0efa6dee296dac32d3205b41f158e0/generated/offsets.json) is a link to the 0.0.1 list which node-cron supports

Thank you. That was giving me some trouble.

**Comment by billythemusical** [comment]
So for example: if I wanna use ``"America/New_York" : 300``, I can pass that in like so... ```cron.schedule(( * * * * * ), { timezone : 300 });```?

**Comment by johnmalatras** [comment]
The key, "America/New_York" in this case, is the `timezone`. 300 is the `offset`. So `cron.schedule(( * * * * * ), { timezone : "America/New_York" })`;

**Comment by LeChienTruc** [comment]
Why is that timezone not exist in vietnam ?

**Comment by dattp** [comment]
> i was select Asia / Ho_Chi_Minh in VietNam, but it is not catch time right, can you explain it for me? thanks a lot.
@LeChienTruc Le
I have checked and there is no support for `Asia/Ho_Chi_Minh`, so I  chose to `Asia/Bangkok` in the same time zone as Vietnam

**Comment by LeChienTruc** [comment]
> > i was select Asia / Ho_Chi_Minh in VietNam, but it is not catch time right, can you explain it for me? thanks a lot.
> 
> @LeChienTruc Le
> I have checked and there is no support for `Asia/Ho_Chi_Minh`, so I chose to `Asia/Bangkok` in the same time zone as Vietnam

I really thanks to your answer, but it is not working for me, i use cron-job-manager in nodejs.
If you have any answer for this question, you can recommend to me, thanks @dattp

**Comment by dattp** [comment]
@LeChienTruc this is node-cron. So, i implemented as:
`cron.schedule('0  19 * * *', () => {
  console.log('Runing a job push notification TKB at 19:00 - test at Asia/Bangkok timezone')
  //TODO
}, {
  scheduled: true,
  timezone: 'Asia/Bangkok'
})`
and it worked!

**Comment by LeChienTruc** [comment]
> @LeChienTruc this is node-cron. So, i implemented as:
> `cron.schedule('0 19 * * *', () => { console.log('Runing a job push notification TKB at 19:00 - test at Asia/Bangkok timezone') //TODO }, { scheduled: true, timezone: 'Asia/Bangkok' })`
> and it worked!

This cron is not manages many jobs at once by keys, it just add single job.
Anyway, thanks @dattp

**Comment by madurapa** [comment]
https://www.inmotionhosting.com/support/website/tz-ref-table/
