### ISSUE TITLE
Dynamically adding and removing crons problem

### ISSUE THREAD

**Issue by xavicolomer** [node-cron/node-cron#135]
Hi there!

I'm facing a problem when adding and removing crons dynamically. 

Apparently destroy works fine, but for some reason, when adding new crons after a first set of crons started (server loads crons from database and starts initial crons)

I get this error on the new crons:
TypeError: this.execution is not a function
    at Promise (........./node_modules/node-cron/src/task.js:52:23)

Any idea?

**Comment by TDola** [comment]
Let's get the obvious out of the way.

When you call cron.schedule(time, function), you have verified your passing a function and not something else, like  string representing a function?

**Comment by xavicolomer** [comment]
`cron.schedule(cron.schedule, callback);`

Yes, it's a function actually the first ones work.

**Comment by xavicolomer** [comment]
Let's get the obvious out of the way, I'm stupid. xD

The second time, when dynamically I wasn't adding the callback

Sorry

**Comment by TDola** [comment]
You could add an issue to the git that the schedule function should throw if a required parameter like the callback is missing.
