### ISSUE TITLE
Q: Is node-cron affected by node issue fixed in 10.9.0?

### ISSUE THREAD

**Issue by eharrow** [node-cron/node-cron#145]
Hi

I am currently using node-schedule that has a reported issue that after long periods the scheduler fails to "wake up" - https://github.com/node-schedule/node-schedule/issues/473.  The issue is due to this node issue https://github.com/nodejs/node/issues/22149 now fixed in 10.9.0 - I think that node-cron, because it uses setTimeout() as opposed to setInterval(), is not affected - true?  I can't find any reports of issues like https://github.com/node-schedule/node-schedule/issues/473 so I hope to change to this module.

Can you confirm?

**Comment by TDola** [comment]
I can't confirm much but I can say I have been using this in production for almost a year now and have had no issues with schedules stopping.  Ours now runs over 300 schedules, usually 60 every 5 minutes.  I do occasionally have issues with it firing twice in a row when the server is very busy, but that was solved by double checking a last run time in the schedule to make sure it is actually running the schedule I asked for, and making sure the schedule callback has no long running code in it to cause an event loop delay.  It just childprocess spawns 60 or so tasks on each schedule.
