### ISSUE TITLE
Error: Invalid timezone America/Argentina/San_Luis

### ISSUE THREAD

**Issue by shamirtv** [node-cron/node-cron#149]
When configuring the time zone of san luis argentina I get the following error

Error: Invalid timezone America/Argentina/San_Luis

Agradezco su atención.

**Comment by alonisser** [comment]
Run ```npm version``` in your project - what 'tz' version are you seeing,
My guess - an older one, and some of the older ones do not support All timezones

**Comment by merencia** [comment]
moving to moment-timezone #248
