### ISSUE TITLE
Firebase Cloud Functions - Long Cron Time

### ISSUE THREAD

**Issue by yuricamara** [node-cron/node-cron#158]
Hi,

Does this library work well in CF even with long time, such as days?
I read somewhere that CF can have problems with long cron time.

Thanks!

**Comment by RMHonor** [comment]
If you're looking at using cron jobs, they won't behave well in a serverless world. Functions only have a server(s) when they're required (referred to as cold starts), and so a cron process won't be able to run if there's no server running.

You'll want to look into some kind of scheduling solution, such as cloud messaging, or there are free services out there that just hit a URL at a specified time.

**Comment by yuricamara** [comment]
Thanks, @RMHonor
