### ISSUE TITLE
Running a job from a given minute

### ISSUE THREAD

**Issue by andrewsteadcc** [node-cron/node-cron#163]
I am trying to implement this rule: `7/15 * * * *` but I get the following error:
"7/15 is a invalid expression for minute"

If I replace the 7 for a * everything is fine but I want the script to have a random start minute because I am running multiple instances of the same API and I don't want all the APIs to hit the server at the same time

My use case is this
```javascript
const random_minute = Math.floor(Math.random() * 59) + 1;
cron.schedule(random_minute+"/15 * * * *", function() {
  console.log("run task every 15 minutes");
});```

**Comment by RMHonor** [comment]
If you want to have a random start time, you'll need to specify the 4 individual intervals:

```javascript
const random_minute = Math.ceil(15 * Math.random());
cron.schedule(`${random_minute},${random_minute + 15},${random_minute + 30},${random_minute + 45} * * * *`, function() {
  console.log("run task every 15 minutes");
});
```

**Comment by andrewsteadcc** [comment]
Thanks very much.
Never realised you could do that, great workaround
