### ISSUE TITLE
Seconnds not working

### ISSUE THREAD

**Issue by adadgio** [node-cron/node-cron#166]
Contrary to the docs, this does actually not run every 5 seconds: 

cron.schedule('5 * * * * *', () => {
    console.log('running a task every 5 sec')
})

**Comment by oferze** [comment]
For all the lost souls that arrived here, the reason is that you need to use an interval syntax: `*/5` , such as:

```
cron.schedule('*/5 * * * * *', () => {
  console.log('running a task every 5 sec')
});
```
