### ISSUE TITLE
Ruining cron on every first day of the month

### ISSUE THREAD

**Issue by alan19031216** [node-cron/node-cron#169]
Hello, i'm a new guys to use cron. So, i would like to use cron in every first day of month.

Example: In first day of the Jan (1 / 01)  will make a function and coming to first day of the Fed (1 / 02) will also make a same function.

I have do some example but dont know which one is correct or both are wrong. 

https://crontab.guru/#1_0_1_1-12_*
https://crontab.guru/#1_0_*/2_1-12_*

**Comment by merencia** [comment]
hello @alan19031216 

the right cron syntax for that is:  `0 0 1 * *`
```
  ┌──────────── minute
  │ ┌────────── hour
  │ │ ┌──────── day of month
  │ │ │ ┌────── month
  │ │ │ │ ┌──── day of week
  │ │ │ │ │
  │ │ │ │ │
  0 0 1 * *
```

This expression will match every first day at 00:00 am every month.

As a plus, I recommend to think about the hour that you cron should run, for example, 03:00 am: 
`0 3 1 * *`

**Comment by haifahrul** [comment]
How about day end of month?

*CASE*
Day every month sometimes 28, 29, 30, 31 .

The querstion is : how to handle running a job every end of month?

**Comment by haifahrul** [comment]
**Solved**
```js
var cron = require('node-cron');
var moment = require('moment');

var task =  new cron('0 00 16 28-31 * *, function() {
  if (isLastDayOfMonth()) {
    doSomeStuff()
  }
}, null, true, 'America/Los_Angeles');

function isLastDayOfMonth(){
  const currentDay  =  moment().format('YYYY-MM-DD');
  const lastDayOfCurrentMonth  =  moment(date).endOf('month').format('YYYY-MM-DD');

  if (currentDate === lastDayOfCurrentMonth) {
    return true;
  } else {
    return false;
  }
}

function doSomeStuff(){
  // your task here.
}
```

The cron will be run every 28 - 31 day, and then check whether current day is a last day of current month. And it's work.

I have add in day_of_month function to check it, if user input L, then day_of_month will be set to 28-31

**Comment by GabeAtWork** [comment]
See #147
