### ISSUE TITLE
Task on specific hour doesn't work

### ISSUE THREAD

**Issue by AmrSaber** [node-cron/node-cron#171]
When I try to run a task on a specific hour of the day, something like ..
```js
const task = cron.schedule(`0 6 * * *`, async () => {
    // some logic
});
```
it dosn't work, the task is never called.

I made a work around that works though: I ran the task every hour (this one works) and do a manual check if that's the hour I want (using [moment](https://github.com/moment/moment)).

```js
const task = cron.schedule(`0 */1 * * *`, async () => {
    if (moment().hours != 6) return;
    // some logic
});
```

**Comment by g33k44** [comment]
Make sure that the timezone configuration is correct on your server. node-cron defaults to UTC timezone if you didn't set the timezone.

**Comment by zmays** [comment]
I may be having the same issue

```
import cron from 'node-cron'
import { forEach } from 'lodash'
import { logger } from './logger'
import { myTask } from 'redacted'

export function createSchedule(minute: number | string = "*", hour: number | string = "*", dayOfMonth: number | string = "*", month: number | string = "*", dayOfWeek: number | string = "*") {
	return `${minute} ${hour} ${dayOfMonth} ${month} ${dayOfWeek}`
}

export function createTasks(schedule: string, ...tasks: (() => void)[]) {
	return {
		schedule,
		tasks: tasks.map(f => f.name),
		status: cron.schedule(schedule, () => {
			forEach(tasks, t => {
				try {
					t()
				} catch (e) {
					logger.error('failed-running-scheduled-task', { errorDetails: e })
				}
			})
		},
			{
				scheduled: true,
				timezone: "America/Chicago"
				// @ts-ignore
			}).getStatus()
	}
}

export const schedules = {
	everyMorning: createSchedule(0, 9),
	everyHour: createSchedule(0)
}

export function heartBeat() {
	logger.event('we-are-live', {})
}

export const createAllTasks = () => {
	return [
		createTasks(schedules.everyMorning, myTask),
		createTasks(schedules.everyHour, heartBeat)
	]
}
```

I see the heartbeat, but I don't ever see the task for 9am (or 4am if for some reason the central time setting isn't working.)

**Comment by AmrSaber** [comment]
I found the error to be on the server used, and not from the library.

I use Heroku free application, the process sleeps after 30 minutes of inactivity, so no tasks are executed after those 30 minutes.

I apologize for the misunderstanding, and I will close the issue, please pardon my ignorance.
