### ISSUE TITLE
[bug] Incorrect cron validation

### ISSUE THREAD

**Issue by luizwbr** [node-cron/node-cron#182]
I always got the error same after set an specific cron pattern expression:  
`0 1-16/3 * * 2/4`

This cron is valid, but node-cron says not: 
> 2/4 is a invalid expression for week day

Is there something I can do without changing the cron expression?

**Comment by 2kindsofcs** [comment]
To use step values, the number to split should be same or bigger than the divisor. 2/4 means "divide 2 with range 4". 2 is smaller than 4. so it can't be divided with range 4. 

> Step values can be used in conjunction with ranges, following a range with '/' and a number. e.g: 1-10/2 that is the same as 2,4,6,8,10. Steps are also permitted after an asterisk, so if you want to say “every two minutes”, just use */2.

**Comment by luizwbr** [comment]
Thanks!
