### ISSUE TITLE
Release without Open Collective

### ISSUE THREAD

**Issue by icbat** [node-cron/node-cron#191]
Hi!

My company uses this library in production. We experienced issues with OpenCollective; to work around this, we installed node-cron directly from Github. We are now no-longer able to do so, so we'll be unable to use this library until a new release is cut without OpenCollective, since the latest published version still has OpenCollective.

I noticed OpenCollective has already been removed, just not published as such. As a stop-gap, I cloned the repo and published whatever was current to: https://www.npmjs.com/package/node-cron-no-open-collective. I would love to delete this and just use this package =)

Thanks!

**Comment by bozzmob** [comment]
@icbat Hi, Just asking out of curiosity, how is OpenCollective stopping your Organization from using this project? Are there any legal issues that I should be aware of?

**Comment by kpatrick** [comment]
I presume it is failing the CI build.  Lots of reports about it on OpenCollective page.

**Comment by icbat** [comment]
It was indeed failing CI builds. I'm no longer with that organization, so I'm unable to pull the exact error we were seeing.

**Comment by kpatrick** [comment]
We ended up using node-schedule instead.

**Comment by M123-dev** [comment]
hello @bozzmob, for me the normal package isn't working, because heroku always throws:
```
sh: 1: opencollective-postinstall: Permission denied
npm ERR! code ELIFECYCLE
```
