### ISSUE TITLE
Any new releases coming soon?

### ISSUE THREAD

**Issue by TDola** [node-cron/node-cron#193]
I am starting to see the double, and sometimes quadruple execution of tasks error more and more.  Hoping there is a release coming that addresses some of the open and closed issues?

**Comment by thedeceptio** [comment]
When did you start seeing this issue? It has been happening to me for almost a week. All the tasks are being executed twice

> I am starting to see the double, and sometimes quadruple execution of tasks error more and more. Hoping there is a release coming that addresses some of the open and closed issues?

**Comment by TDola** [comment]
> When did you start seeing this issue? It has been happening to me for almost a week. All the tasks are being executed twice
> 
> > I am starting to see the double, and sometimes quadruple execution of tasks error more and more. Hoping there is a release coming that addresses some of the open and closed issues?

https://github.com/node-cron/node-cron/issues/120

**Comment by jon-malave** [comment]
@TDola are you seeing issues mostly with 1 minute interval scheduled jobs? I will probably have 1 hour minimum schedule job use case on my end... I'm curious if I will also start to face issues if my app scales up in the near future while using node-cron. 

I second this post! Any updates on new release? I think node-cron is an awesome library but seems to have some bugs here and there. I'm considering going with Bull.js but i'm still not 100% sure as it just seems like over-kill for my needs.

**Comment by TDola** [comment]
@jon-malave The bug mostly happens when the computer hardware is maxed out.  I mitigated the issue somewhat by setting the process priority in Windows to maximum.  I have no idea if it happens in other environments.
I am also not certain if it's truly this plugins fault.  This plugin is ultimately relying on `setInterval(yourTask,1000)` to repeatedly check to see if the time you provided for your task is now.  This interval get's busy and skips a few, lumping them all together in 1 bulk.

You can cover for some of the issues by debouncing your own task, and store your tasks as an array of objects and functions.  And set a `isRunning` style object property that is subsequently checked.  This way if your task is accidentally run twice while the first task is waiting on an async operation to complete, you can cancel it.  Also, if you have a lot of tasks running at the same time.  Collect them up into an array of runnable tasks then execute them, that way node-cron has enough time to call all your tasks before you start any blocking code.

**Comment by merencia** [comment]
Hey, I'm really sorry about my almost no time dedicated to node-cron, I've released the version 3.0.0 few days ago.
