### ISSUE TITLE
Executing PHP url

### ISSUE THREAD

**Issue by abdkaviani** [node-cron/node-cron#195]
Hello

I only need to executing PHP url at 10:00 everyday in my localhost
My url is: http://localhost/1.php  (that returns no output)

Can I use node-cron and how do I execute this url?

`var CronJob = require('cron').CronJob;
new CronJob('* * * 10 * *', function() {
  //execute URL
}, null, true, 'America/Los_Angeles');`

Thanks a lot

**Comment by TDola** [comment]
Sure, just fetch the URL
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API
If your local host is running a php providing server, that should be all that is needed.

Alternatively, just spawn the php.exe with the script you want to run as a parameter.

**Comment by abdkaviani** [comment]
It works for automatic backup db!
Thanks a lot :)

`var cron = require('node-cron');
const fetch = require('node-fetch');

cron.schedule('0 30 21 * * *', () => {
  console.log('Auto Backup Start 21:30:00 ...');
  fetch('http://x.x.x.x/php/backup_automatic.php');
});
`
