### ISSUE TITLE
Need help in skipping cronjob when already scripts for previous cronjob are running

### ISSUE THREAD

**Issue by CodeWithSid675** [node-cron/node-cron#214]
I have written a cron job as given below

var cron = require('node-cron');
var taskMap = {};
 let job = cron.schedule('*/1 * * * * ', ()=>{
    var shell = require('./utils/child_helper');

    var commandList = [
        "node  *****",
        "node  *****", 
        "node  ******"
    ]
    
     shell.series(commandList , function(err,res){
    //    console.log('executed many commands in a row');
        console.log('done')
    });
});

which need to run on every 1 min but the scripts inside the cron may take more than 1 min.
I need to skip the cron for the moment when the scripts are still running .
Can anyone help me on it.

Calling cron from app.js as below code

const express = require('express');
const app = express();
const bodyParser = require('body-parser');
var port = 3000;
require('./cronController').job.start();

app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
app.listen(port , ()=>{
    let dateTime = new Date();
    let message = 'Server is running on Port :- ' + port + ' started at :- ' + dateTime;
    console.log(message);
});

**Comment by franzjosefwirtz** [comment]
One option could be to use the not documented function getStatus(), which might return 'scheduled', 'running', 'stoped' (one p only), 'failed', 'destroyed'.

```javascript
let job = cron.schedule('*/1 * * * * ', ()=>{
if(job.getStatus() === 'running') {
  return;
}
// do the normal stuff
});
```

Another option would be to track the running status in your task function.

**Comment by merencia** [comment]
Hi @CodeWithSid675, even you prevent to that if you are running your application in multiple instances you probably need to use some distributed lock to prevent that.

https://redis.io/topics/distlock

Another good option is to avoid large processing inside a node-cron task. to do so, you can start the process, for example by putting a message in a queue.

but the @franzjosefwirtz option is fine for single instance process.

**Comment by maon-fp** [comment]
> One option could be to use the not documented function getStatus(), which might return 'scheduled', 'running', 'stoped' (one p only), 'failed', 'destroyed'.
> 
> ```js
> let job = cron.schedule('*/1 * * * * ', ()=>{
> if(job.getStatus() === 'running') {
>   return;
> }
> // do the normal stuff
> });
> ```

This is not working for me. The `job.getStatus()` seems to run infinitely.

I solved it by a simple variable:

```js
let isRunning = false;

cron.schedule('*/1 * * * * ', ()=>{
  if(isRunning) return;
  isRunning = true;
  // do the normal stuff
  isRunning = false;
});
```
