### ISSUE TITLE
Dependency tz-offset returning wrong value

### ISSUE THREAD

**Issue by jplandry908** [node-cron/node-cron#217]
i.e. America/New_York is currently returning 300, but should be returning 240. I tried v0.0.1 (the version this package uses) as well as v0.0.2 (the version currently available). Both version returning 300 so all jobs are 1 hour off.

I suggest maybe moving this to moment instead to resolve this.

For example:

var tzOffset = require("tz-offset");
**WRONG UTC OFFSET (used in the code today):**
console.log(tzOffset.offsetOf("America/New_York"));

var moment = require("moment");
var tz = require("moment-timezone");
**CORRECT OFFSET:**
console.log(moment().tz("America/New_York").format('Z'));
**CORRECT DATE AND TIME:**
console.log(moment().tz("America/New_York").format());

**Comment by jplandry908** [comment]
FYI - If anyone is experiencing this issue and wants to apply a quick fix without rewriting too much code, I did the following to fix it.

**INSTALL:**
 - moment
 - moment-timezone

**MAKE THE FOLLOWING CHANGES IN 'scheduled-task.js' ...**

**DECLARE:** 
`var moment = require("moment");`
`var tz = require("moment-timezone");`

**CHANGE THIS FUNCTION:**
`this.task = () => {`
`var date = new Date();`
`if(timezone){`
`//date = tzOffset.timeAt(date, timezone);`  **//COMMENT OR REMOVE THIS LINE**
`let offset = moment.tz(moment.utc(), timezone).utcOffset();`   **//ADD THIS LINE**
`date = new Date(moment(date).add(offset, 'minutes').format());`   **//ADD THIS LINE**
`}`
`this.tick = setTimeout(this.task, 1000 - date.getMilliseconds() + 1);`  
`task.update(date);`
`};`

**Comment by itsjustcon** [comment]
I'm experiencing the same issue. All of my tasks are running 1 hour later than expected.

**Comment by ecoleman** [comment]
There is a pending pull request to fix offsets: https://github.com/node-cron/tz-offset/pull/11
