### ISSUE TITLE
Invalid timezone Asia/Manila

### ISSUE THREAD

**Issue by mannyvergel** [node-cron/node-cron#222]
Seems with other libraries Asia/Manila timezone works except for node-cron. Please advise.

**Comment by Pyromonk** [comment]
It's supposed to work with node-cron as well, but I've tried a bunch of 0-offset timezones from [the official list](https://raw.githubusercontent.com/node-cron/tz-offset/master/generated/offsets.json), and none of them work. Something's wrong with node-cron in that respect.

**Comment by merencia** [comment]
Hi there, sorry about the delay.
I've released a new version using moment-timezone
https://github.com/node-cron/node-cron/pull/248
