### ISSUE TITLE
Seconds is not working

### ISSUE THREAD

**Issue by tbhaxor** [node-cron/node-cron#224]
My code

```js
function handleSubscritionExpiry() {
  console.log("Now:", moment().toDate());
}

const subscription = cron.schedule("1 * * * * * ", handleSubscritionExpiry, {
  scheduled: false
});

exports.subscription = subscription;
```

![Uploading image.png…]()

**Comment by Uzlopak** [comment]
Cron has a 60 sec granularity.

**Comment by darthzeran** [comment]
same
```
cron.schedule('15 * */1 * *', () => {
	console.log('running every 15 sec')
})
```

**Comment by tbhaxor** [comment]
I found a better solution, [`node-schedule`](https://www.npmjs.com/package/node-schedule)

**Comment by ZimGil** [comment]
> My code
> ```javascript
> function handleSubscritionExpiry() {
>   console.log("Now:", moment().toDate());
> }
> 
> const subscription = cron.schedule("1 * * * * * ", handleSubscritionExpiry, {
>   scheduled: false
> });
> 
> exports.subscription = subscription;
>```

You're settings `scheduled` to false so it won't start until you use `subscription.start()`. do you use it anywhere else?

**Comment by ZimGil** [comment]
> same
> 
> ```
> cron.schedule('15 * */1 * *', () => {
> 	console.log('running every 15 sec')
> })
> ```

@darthzeran This should actually run ever 15 **minutes** You may want to change `'15 * */1 * *'` into `*/15 * * * * *`

**Comment by tbhaxor** [comment]
> t anywhere else?

@ZimGil yes in index.js i m using, its working but after every one minute

**Comment by ZimGil** [comment]
@tbhaxor Oh yeah now I see.
The cron expression `1 * * * * *` means: Every ***1st second*** of every minute of every hour etc...
If you want your code to execute every ***second*** you may want to convert it into `* * * * * *` which means Every second of every minute etc...
