### ISSUE TITLE
The library does not support the latest time zone, for example 'Asia/Calcutta'. Please update the time zone list

### ISSUE THREAD

**Issue by manishrana87** [node-cron/node-cron#247]

**Comment by AdwaithHSivam** [comment]
For the time being u can use `'Asia/Kolkata'` instead

**Comment by manishrana87** [comment]
Thanks, @AdwaithHSivam I have done that already, but my suggestion was to update the library time zone list so that we don't need to manually write the Zone name.

**Comment by jgonera** [comment]
Another option would be to stop using `tz-offset` and replace it with built-in `Intl.DateTimeFormat` which is now pretty widely supported across Node.js and modern browsers: https://caniuse.com/mdn-javascript_builtins_intl_datetimeformat

**Comment by merencia** [comment]
I've released a new version, and started using moment-timezone.

https://github.com/node-cron/node-cron/pull/248
