### ISSUE TITLE
Is this library being maintained?

### ISSUE THREAD

**Issue by leandromatos-hotmart** [node-cron/node-cron#251]
The last update happened a long time ago.

**Comment by P4sca1** [comment]
Hey @leandromatos-hotmart,
I created a similar library here: https://github.com/P4sca1/cron-schedule
Since this is my first open source project, I would love to get some feedback! :)

**Comment by jgonera** [comment]
Found https://github.com/jaclarke/cronosjs which looks like a promising replacement.
