### ISSUE TITLE
Error en la zona horaria "America/Mexico_City"

### ISSUE THREAD

**Issue by rey1503** [node-cron/node-cron#254]
A pesar de que las fechas coincidan el programa no ejecuta lo que hay dentro, se desconoce el motivo
![Screen Capture_20201013174520](https://user-images.githubusercontent.com/72836553/95923949-3880c100-0d7c-11eb-90f8-642afa554bf8.png)
![Screen Capture_20201013174523](https://user-images.githubusercontent.com/72836553/95923998-564e2600-0d7c-11eb-96f8-c0fb0bdceac5.png)

**Comment by falsepopsky** [comment]
Guardalo en una constante y ejecutalo...

```
const mexico = cron.schedule(
  '42 23 13 11 5',
  () => {
    console.log('hola mexico.');
  },
  {
    scheduled: true,
    timezone: 'America/Mexico_City',
  }
);

mexico.start();
```

**Comment by rey1503** [comment]
> el código está bien, lo probé y me funciona, de última lo guardas en una constante y ejecutás ...
> 
> ```
> const mexico = cron.schedule(
>   '42 23 13 11 5',
>   () => {
>     console.log('hola mexico.');
>   },
>   {
>     scheduled: true,
>     timezone: 'America/Mexico_City',
>   }
> );
> 
> mexico.start();
> ```

**Comment by rey1503** [comment]
Es cierto ahora funciona correctamente Gracias
