### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by merencia** [node-cron/node-cron#255]
Hi there!

I'm not able to pay attention to this project as I wanted to.

Would someone like to help maintain the project?

**Comment by gary1998** [comment]
Hi there!
I would love to contribute 🙂

**Comment by P4sca1** [comment]
I maintain a similar project and plan to extend its functionality in the future.
It already covers most of what node-cron can do.
You can find it here: https://github.com/cron-schedule

**Comment by shusson** [comment]
There's also https://github.com/node-schedule/node-schedule
