### ISSUE TITLE
Expression for Third Tuesday of every month starting from Mar 2021 to April 2022

### ISSUE THREAD

**Issue by HackinwaleDev** [node-cron/node-cron#263]
I am having issue creating an expression to satisfy this (see the title above)
I read from [here](http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/tutorial-lesson-06.html) and thought I could apply same to Node-cron but seems not working

Here is my expression:

0 30 5 * Mar-Apr Tue#3 2020-2021

Please assist me with a way to write this expression to be compatible with Node-Cron @merencia 

Thank you.

**Comment by sp-devi** [comment]
I'm not sure if this expression is possible on node-cron. And also there is no YEAR field in node-cron. You can do something to the execution to copy the behavior for next year, but not the expression.

**[30 5 15-21 MAR-DEC TUE]** 
This one according to Crontab.guru runs “At 05:30 on every day-of-month from 15 through 21 and on Tuesday in every month from March through December.”

**Comment by HackinwaleDev** [comment]
Thank you friend. I have tried playing with crontab.guru but what I got that is close is this: 
[0 18 */2 * 3] - “At 18:00 on every 2nd day-of-month if it's on Tuesday.”

Is there a way I can tweak this to give me  “At 18:00 on every 2nd Tuesday-of-month”

Thank you.

**Comment by sp-devi** [comment]
[0 18 */2 * Tue] -> [0 18 8-14 * TUE]

This one becomes “At 18:00 on every day-of-month from 8 through 14 and on Tuesday.

Essentially the same thing with what you want. The task will only run **IF** the day is 8 through 14 **AND IF** it is TUESDAY.
Or run the task if it's Tuesday on day 8 - 14. 
Any Tuesday that falls on the range of 8 - 14 is most definitely the 2nd Tuesday of the month.

**Comment by HackinwaleDev** [comment]
Hey there, thanks again for looking out for me.

I tried the  [0 18 8-14 * TUE] and here is what I observed
1 - I got report every day from 8 - 14 including non Tuesdays
2 - The expression does not translate to "On 8th through 14th day-of-month _IF_ it is TUESDAY" instead it translated to "On 8th through 14th day-of-month **AND** _IF_ it is TUESDAY". This I guess is the reason for (1) above.

Do you think there is a way AND can be taken off the interpretation of the expression?

Regards.

**Comment by sp-devi** [comment]
@HackinwaleDev , you are right. I guess there is no easy way for this using the expression alone.
You can still try this [0 18 8-14 * *] and have a separate filter condition(for Tuesday in this case) inside the start() method.

**Comment by HackinwaleDev** [comment]
Thank you.

I can use momentjs to check if the day it Tuesday before excuting the function inside the schedule.

I hope this make sense.

For example,
`let task = cron.schedule("0 18 8-14 * *", () => {
    if(moment.day() == 'Tuesday' or moment.day() == "2"){
         // code goes here
    }
})`

I bet that should work. I will implement it now and see.

Thank you

**Comment by HackinwaleDev** [comment]
Here is how I eventually solved it.

let task = cron.schedule("0 18 8-14 * *", () => {
                ...
    if (freq === "Once per Month") {
       if (parseInt(config['month-specific-day']) === moment().day())
             myReport.sendCustomReport(freq, config, cReport);
       else console.log("Report Postponed.");
    }
               ...
}

I hope this helps someone too.

Goodluck.
