### ISSUE TITLE
Question: Does node-cron use cron behind the scenes ?

### ISSUE THREAD

**Issue by GrosSacASac** [node-cron/node-cron#265]
If yes, does that mean that after the node program runs the task will be repeated by cron ?

**Comment by tadeork** [comment]
I know this isn't a full answer but by reading the source code I came to the conclusion that this line explains what is happening BTS https://github.com/node-cron/node-cron/blob/94c139fd418571106fc12c5d55817187488f460f/src/scheduler.js#L35

**Comment by GrosSacASac** [comment]
So no
