### ISSUE TITLE
cron scheduled to run on every 21 hours but runs also at 12AM

### ISSUE THREAD

**Issue by Mohamed-Muthu** [node-cron/node-cron#275]
My cron pattern is 0 0 */21 * * *. It should run at every 21 hours. But it runs at 21:00 and also at 00:00. It means that it runs twice in a day, one at 9PM and another at 12AM. Kindly advise how to schedule to run the cron every 21 hours.

**Comment by Mohamed-Muthu** [comment]
Observed this issue in latest version too.

**Comment by kokno** [comment]
Hi, it looks like the pattern of your cron is invalid.

**Comment by Mohamed-Muthu** [comment]
> 
> 
> Hi, it looks like the pattern of your cron is invalid.

I agree. I will close this ticket. Would it be possible to run the cron every 21 hours?
