### ISSUE TITLE
TypeError: task.destroy is not a function

### ISSUE THREAD

**Issue by pawarss1** [node-cron/node-cron#288]
Trying to execute a simple code snippet provided on npm. This is related to node-cron.

```
const cron = require('node-cron');

const task = cron.schedule('* * * * *', () =>  {
  console.log('will not execute anymore, nor be able to restart');
});

task.destroy();

```
Output- 
task.destroy();
     ^
TypeError: task.destroy is not a function

![Screenshot (452)](https://user-images.githubusercontent.com/37259966/119626506-eb43f200-be28-11eb-9d79-ae5c8f777e09.png)

**Comment by komyg** [comment]
I have the same problem.

**Comment by ixuz** [comment]
I got the same issue, using version: `3.0.0`
