### ISSUE TITLE
CRON jobs are not getting executed on AWS Lambda

### ISSUE THREAD

**Issue by ahmad-invozone** [node-cron/node-cron#295]
I am running a job every minute on AWS Lambda (ServerLess deployments). 
But it is not getting executed.

Environment: AWS LAMBDA

var cron = require('node-cron');

cron.schedule('* * * * *', () => {
  console.log('running a task every minute');
});

**Comment by merencia** [comment]
I don't recommend using `node-cron` with AWS Lambda...
Also, Lambda already have a solution for scheduled tasks:
https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-run-lambda-schedule.html
