### ISSUE TITLE
When exactly this cron runs

### ISSUE THREAD

**Issue by gagansharma** [node-cron/node-cron#307]
Generally when we schedule a cron job we have five stars * * * * *

But in you documentation you mention that we can use Six Stars. So please clearify my doubt that when the below cron runs

cron.schedule('00 9 * * * *', function () {
  commonmethods.testingCron();
},{
  scheduled: true,
  timezone: "Asia/Kolkata"
});

**Comment by bilal-08** [comment]
the last star from left handside represents secounds, it's optional tho
