### ISSUE TITLE
Customizing package to run task every minute

### ISSUE THREAD

**Issue by st-fresh** [node-cron/node-cron#314]
I have a task that will only ever need to run every minute (60seconds)
Is there any guidance on how to rebake node-cron to be implemented for running a task every minute?
I see `expressions[0] = convertAsterisk(expressions[0], '0-59');`
So if a minute is the only time allotment I need to ever schedule a task for there must be a way to cut down the project to size that it would be customized to run such a task
If this isn't available with node-cron then is there any guidance to use momentjs to implement this type of custom scheduler?

**Comment by Hexagon** [comment]
I would recommend https://github.com/hexagon/croner, which has a similar interface tog cron, but without external dependencies. 

However, THE most compact way of running a task every minute is with vanilla JavaScript, is by using either setInterval or a recursive implementation of setTimeout, with a timeout of 60000ms.

**Comment by merencia** [comment]
@st-fresh If I understand right, `node-cron` already supports that. To execute a task every minute you may use this pattern: `0 * * * * *`. I will execute your task every minute on second 0.
