### ISSUE TITLE
Setting up on Cloudrun

### ISSUE THREAD

**Issue by simplenotezy** [node-cron/node-cron#322]
Has anybody had any experience with setting this up on a Cloud Run instance? I imagine setting the minimum amount of instances to be 1, so there's always a service running, but would that be sufficient?

**Comment by merencia** [comment]
node-cron does not demand any kind of horizontal scaling that depends on your application.

important facts:
 - If you are scheduling the same tasks in 2 different instances that will pe performed twice one in each instances.
 - the lib does not have any kind of control about what is performed, so, to scale that your taks must be indepotent and/or use something like a distributed lock.
