### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by soroushBgm** [node-cron/node-cron#324]
This is my setup
`
cron.schedule('10 * * * * *', controller.updateStatus);`

It must run every 10 seconds, but it runs every minute or so. This is the log of seconds each time the function has run:

7
67
127
187
.
.
.

**Comment by merencia** [comment]
can you make a test calling another function rather than `controller.updateStatus`? 

If your job take more than 10 seconds, the next execution will be performed when the previous one was finished.

**Comment by soroushBgm** [comment]
`controller.updateStatus` is not a complicated function. Just a simple DB update. Currently I'm using `setTimeout` with no problems.

**Comment by merencia** [comment]
I think I know what is happening... Following the cron tab syntax the pattern : `10 * * * * *` means: every second 10, of any minute, of any hour of any day, of any month of any day of week. Basically your are performing your task once by minute when the second was 10.

To fix that, you may do something like: `*/10 * * * * *` it will perform your task at seconds 10, 20, 30, 40, 50, and 0
