### ISSUE TITLE
Tasks run immediately when cron.schedule() is called

### ISSUE THREAD

**Issue by tsongas** [node-cron/node-cron#337]
I'm scheduling jobs like this:
```
async function init() {
  await startApolloServer()
  cron.schedule('0 0 * * * *', sendCalendarReminders)
  cron.schedule('0 0 * * * *', sendCaseReminders)
  cron.schedule('0 */1 * * * *', sendEmails)
}

init()
```
however my tasks run when init() is called, as well as at their scheduled time, and I'm not sure why. The functions I'm calling are async functions i.e.
```
export const sendEmails = async () => {
...
}
```
but I would only expect them to run when `init()` is called if I made the mistake of calling them when passing them to `cron.schedule` i.e. `cron.schedule('0 0 * * * *', sendCalendarReminders())` which I'm not doing. Any ideas appreciated!

**Comment by Hexagon** [comment]
@tsongas Try if you experience the same issue with https://github.com/hexagon/croner

**Comment by JacquelineJ96** [comment]
Hi tsongas! I tried to reproduce your issue and could not. Is it possible you ran this at exactly the time the job needed to fire? My code is below and shows it does not fire the job when the job is first created/scheduled. 
For a job firing every minute on the dot, you can see the job was created/scheduled at 21:25:54, and then the first job started at 21:26:00.

**File: Issue#337.mjs**
```js
import cron from 'node-cron'
import {logger, sleep} from './log.mjs'

async function init() {
  await sleep(100)
  cron.schedule('0 */1 * * * *', logger) // every minute
  console.log("Cron Scheduled: "+new Date().toISOString())
}

init()
```

**File: log.mjs**
```js
export const logger = async () => {
    console.log("Job Start: "+new Date().toISOString())
    await sleep(200)
    console.log("Job End: "+new Date().toISOString())
    }

export function sleep(ms) {
    let endTime = Date.now() + ms
    while(Date.now() < endTime){}
}
```

**Results**
<img width="399" alt="Screen Shot 2022-04-16 at 5 27 27 PM" src="https://user-images.githubusercontent.com/103853798/163692041-47689523-222d-46d3-baa7-92f9ab5ad25f.png">

**Comment by tsongas** [comment]
Sorry, I was being an idiot. Had leftover code calling my tasks from the bottom of each task file.
