### ISSUE TITLE
Bug with uuid dependency in node-cron@3.0.1

### ISSUE THREAD

**Issue by Choppel** [node-cron/node-cron#355]
With the current version 3.0.1 there was a bug introduced that makes the plugin unusable inside a node project. The module "uuid" is loaded in some files of node-cron but the package.json does not state it as a dependency. node-cron@3.0.1 will break on all systems were uuid is not installed in the main package.json of the node project.
Current workaround is either reverting to 3.0.0 or installing uuid alongside node-cron in your project until this is fixed.

**Comment by vcarl** [comment]
#321 introduced the import but did not update dependencies. `uuid` should be either a peerDep or a dependency

**Comment by mrjackyliang** [comment]
Just basing off a hunch, but I'm also on `3.0.0` and I see the same issue.

**Comment by mrjackyliang** [comment]
Not sure why it didn't happen earlier, but this error happened right after I updated a single package

**Comment by jeffcad** [comment]
I don't know if this could be related, but version 3.0.1 sent my memory usage skyrocketing for my Node.js application on DigitalOcean. On version 3.0.0 the app runs at about 23% memory usage, but 3.0.1 sent it up to 100% and the app reset itself every 6 minutes or so to avoid resource exhaustion. Reverting node-cron back to 3.0.0 solved the problem.

**Comment by Choppel** [comment]
@ugurgunes95
How did downgrad the package? I installed it with `npm i --save node-cron@3.0.0` and that worked.

**Comment by weyert** [comment]
Can't the built-in node's `crypto.randomUUID` be used?
