### ISSUE TITLE
Is it possible to check if the cron job is scheduled or not

### ISSUE THREAD

**Issue by ahsan131-hub** [node-cron/node-cron#382]
I have actually implement a queue in which i saving the all req from client side and i have schedule a cron job the loop through queue and process and empty it.
so i dont want to run cron job when queue is empty, 
and i want to run job when there is some data in cron job.

so i want to conditionally check if the cron job is already running then donot rerun.

**Comment by tangjm** [comment]
When you invoke schedule

**Comment by tangjm** [comment]
Here is one way you could check if a specific task is already running or scheduled.

```javascript
// The function signature of `schedule` lets you pass an optional third argument.
function schedule(expression, func, options)
```

If you pass an object with a 'name' property set to a value of your choice as this third argument, then you can check whether a specific job is scheduled by checking if its 'name' property is in the scheduled tasks Map.

Note that if you do not provide the 'name' property then it will default to a universally unique identifier.

```javascript
const cronJob = require('node-cron'); 

cronJob.schedule("* * * * *", yourFunction, { name: "yourFunctionIdentifier" });

// returns the scheduled tasks, which is a Map of names to scheduled tasks. 
const scheduledTasks = cronJob.getTasks();     

// returns a truth-value indicating if the task identified by "yourFunctionIdentifier" is scheduled 
scheduledTasks.has("yourFunctionIdentifier");   
```

**Comment by Horlando-Leao** [comment]
const cronJob = require('node-cron');

const job1 = cronJob.schedule("* * * * *", yourFunction, { name: "yourFunctionIdentifier" });
const job2 = cronJob.schedule("* * * * *", yourFunction, { name: "yourFunctionIdentifier" });

const jobs = [job1, job2];


const jobsStatus = [];
jobs.forEach((job) => {
  jobsStatus.push({
    name: job.name,
    running: job.options.scheduled === true, // Verifica se o job está em execução
  });
});

console.log(jobsStatus);
