### ISSUE TITLE
Memory leak happening (only 2 cron running)

### ISSUE THREAD

**Issue by RohitLakh** [node-cron/node-cron#404]
I have 2 cron jobs running along with the slack bot which runs once every day at a specific time, but every minute the memory consumption increases. I am also using timezone for running cron. The app is hosted on railway.app.

`node-cron` version: **3.0.8**

Memory graph using `node-cron`

![image](https://github.com/node-cron/node-cron/assets/34619861/4278647b-d9c7-4ede-8ce6-c587a29d6644)

I tried the same code using `cron` library from npm and the memory usage remains at the same level

Memory graph using `cron`
![image](https://github.com/node-cron/node-cron/assets/34619861/ac961af9-8e6c-4296-954b-22ac420cacaf)

**Comment by StefanNedelchev** [comment]
not sure if it's related to the same issue but there currently is a bug that causes huge memory consumption if you provide a `timezone` option to your schedulers. Try checking that out first.

**Comment by StefanNedelchev** [comment]
Maybe fixed now by #366  ?

**Comment by synque-dev-admin** [comment]
@StefanNedelchev the latest version tested was 3.0.3? 
- did you test with timezone option ON?
