### ISSUE TITLE
Tag the v3.0.3 release

### ISSUE THREAD

**Issue by harryzcy** [node-cron/node-cron#407]
I see the v3.0.3 release on npm, but there’s no corresponding [tag on GitHub](https://github.com/node-cron/node-cron/tags). Can we have a tag to know which commit matches the release?

**Comment by vmignot** [comment]
Hello,
I agree with you, a tag would be welcome.
Meanwhile, you can see that this the 3.0.3 starts at this commit : https://github.com/node-cron/node-cron/commit/e65a2d0dca1590f7a4af4ab9d6ec81b5cc4728d6

**Comment by merencia** [comment]
added https://github.com/node-cron/node-cron/releases/tag/v3.0.3
