### ISSUE TITLE
why didn't cron throw the Error

### ISSUE THREAD

**Issue by codenoy** [node-cron/node-cron#414]
code:
```js
// index.js
const cron = require("node-cron");
const task = cron.schedule("* * * * * *", () => {
  console.log("date.now => ", date.now());
});
```
cmd: node index.js

it just hang on and did not exit , no erorr console

**Comment by TobyAjLot** [comment]
What you did there is assigned the return value of cron.schedule to task and did nothing with task.

Try removing the assignment and use cron.schedule directly.

**Comment by codenoy** [comment]
```js
// index.js
const cron = require("node-cron");
const task = cron.schedule("* * * * * *", () => {
  console.log("date.now => ", Date.now()); // fix the Error, date.now() => Date.now()
});
```
I fix the error, it worked succesd and print the timestamp.
Apps should expect crashes, but it not.
