### ISSUE TITLE
can i get time value in scheduled function?

### ISSUE THREAD

**Issue by sechunOH** [node-cron/node-cron#61]
hello, 
i wanna know the value of time when scheduled function called.

example, i set cron job with (* * * * * *) scheduling expression, 
maybe function is called every second, but i log new Date()'s second value in function at first line, this value is shown as 1, 2, 3, 4, 6, 6, 7, ... 
can i get exact time when job excuted in job function?

**Comment by merencia** [comment]
@bchelli first sorry for the very long time to answer your question.

There is no way to get this the right time from now, but I think this is a node-cron issue.

Can you remember if you has done that inside the task function?

**Comment by merencia** [comment]
The bug here is, when a task is scheduled a interval is created, what is happening is the task is checked and performed twice in the same second. I think a previous execution checker should be added to node-cron to prevent this bad behavior.

**Comment by merencia** [comment]
This issue is the same than #38
