### ISSUE TITLE
How can i change time of running cronjob dynamically ? 

### ISSUE THREAD

**Issue by DaniyalGeek** [node-cron/node-cron#65]

**Comment by mateuszfaris** [comment]
Any news in this case ?

**Comment by merencia** [comment]
@DaniyalGeek @mateuszfaris I did not understand the use-case for that.

Can you explain me the behavior that you're looking for?

**Comment by rahajason** [comment]
I think he wants to dynamically change schedule

**Comment by fjeddy** [comment]
Yes, I'm looking for the same behavior, basically I want the administrators to be allowed to define in the CRON schedule themselves through a UI stored in a database.

It's not a problem as is to get the interval from the database on first load, but as is now, then the app has to be restarted every time the value changes.

**Comment by TDola** [comment]
I solved this by watching for changes, storing the ID in app, and if the schedule or anything related to the cron changes for an id, that ID is stopped and re-added with the new parameters.

**Comment by xino1010** [comment]
Thanks @TDola for the info.

Using [https://github.com/miaowing/nest-schedule](Nest-schedule).

- Stop.
- SetTime new Time.
- Start again.

``` 
this.schedulerRegistry.getCronJob(task.id).stop();
this.schedulerRegistry.getCronJob(task.id).setTime(cronTime);
this.schedulerRegistry.getCronJob(task.id).start();
```

**Comment by NiekBeijloos** [comment]
Hi @xino1010 ,

Could you please share your implementation and dependencies?
